repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: end-of-file-fixer
    files: 'repository_service_tuf_api/'
  - id: trailing-whitespace
    files: 'repository_service_tuf_api/'
  - id: check-yaml
    files: '.github/'
- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8
    exclude: docs
- repo: https://github.com/PyCQA/isort
  rev: '5.12.0'
  hooks:
  - id: isort
    args: [-l79, --profile, black, --check, --diff]
- repo: https://github.com/psf/black
  rev: '22.12.0'
  hooks:
  - id: black
    args: [-l79, --check, --diff, .]
- repo: https://github.com/PyCQA/bandit
  rev: '1.7.4'
  hooks:
  - id: bandit
    args: ["-r", "repository_service_tuf_api"]
    exclude: tests
- repo: local
  hooks:
    - id: tox-requirements
      name: run requirements check from tox
      description: Checks if `make requirements` is up-to-date
      entry: tox -e requirements
      language: system
      files: ''
      pass_filenames: false
      verbose: true


name: Update pre-commit Hooks

on:
  push:
    branches:
      - main

jobs:
  update-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Pre-Commit
        run: pip install pre-commit
      - name: Update Pre-Commit Hooks
        run: pre-commit autoupdate
      - name: Commit Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update pre-commit hooks"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}