version: "3.9"

volumes:
  repository-service-tuf-worker-data:
  repository-service-tuf-mq-data:
  repository-service-tuf-storage:
  repository-service-tuf-redis-data:
  repository-service-tuf-pgsql-data:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
     - "repository-service-tuf-mq-data:/var/lib/rabbitmq"
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  redis:
    image: redis:4.0
    volumes:
      - repository-service-tuf-redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  postgres:
    image: postgres:15.1
    ports:
      # 5432 may already in use by another PostgreSQL on host
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - "repository-service-tuf-pgsql-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s

  repository-service-tuf-worker:
    image: ghcr.io/repository-service-tuf/repository-service-tuf-worker:dev
    # Developers: For local build repository-service-tuf-worker, uncomment the line below
    #   On repository-service-tuf-worker, run make build-dev
    #
    # image: repository-service-tuf-worker:dev
    volumes:
      - repository-service-tuf-storage:/var/opt/repository-service-tuf/storage
      - "./tests/files/key_storage:/var/opt/repository-service-tuf/key_storage"
    environment:
      - RSTUF_STORAGE_BACKEND=LocalStorage
      - RSTUF_KEYVAULT_BACKEND=LocalKeyVault
      - RSTUF_LOCAL_STORAGE_BACKEND_PATH=/var/opt/repository-service-tuf/storage
      - RSTUF_LOCAL_KEYVAULT_PATH=/var/opt/repository-service-tuf/key_storage
      - RSTUF_LOCAL_KEYVAULT_KEYS=online.key,strongPass
      - RSTUF_BROKER_SERVER=amqp://guest:guest@rabbitmq:5672
      - RSTUF_REDIS_SERVER=redis://redis
      - RSTUF_SQL_SERVER=postgresql://postgres:secret@postgres:5432
      - RSTUF_WORKER_ID=dev
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: python:3.10-slim-buster
    command: python -m http.server -d /var/opt/repository-service-tuf/storage 8080
    volumes:
      - repository-service-tuf-storage:/var/opt/repository-service-tuf/storage
    ports:
      - "8080:8080"

  repository-service-tuf-api:
    build:
      context: .
    entrypoint: uvicorn app:rstuf_app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    environment:
      - RSTUF_BROKER_SERVER="amqp://guest:guest@rabbitmq:5672"
      - RSTUF_REDIS_SERVER="redis://redis"
    volumes:
      - ./:/opt/repository-service-tuf-api:z
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      repository-service-tuf-worker:
        condition: service_healthy
