name: Tests and Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ "3.9", "3.10", ]

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install tox and coverage
      run: pip install tox tox-gh-actions

    - name: Run Python tests
      run: tox

    - name: Codecov
      uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
      with:
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true