name: Publish Container Image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: "Image version"
        default: "dev"
        type: string
        required: False
  workflow_call:
    inputs:
      image_version:
        description: "Image version"
        default: "dev"
        type: string
        required: False

jobs:
  publish_container_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release tag
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      with:
        fetch-depth: 0
        ref: ${{ inputs.image_version }}

    - name: Set default Python version
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
      with:
        python-version: '3.10'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349

    - name: Login to GitHub Container Registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64 #,linux/arm/v7,linux/arm/v8
        tags: |
            ghcr.io/repository-service-tuf/repository-service-tuf-api:${{ inputs.image_version }}
        build-args: |
          RELEASE_VERSION=${{ inputs.image_version }}
