name: Build and Publish (dev) Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/publish_docker_dev.yml'
      - 'app.py'
      - 'entrypoint.sh'
      - 'Dockerfile'
      - 'requirements**'
      - 'repository_service_tuf_api/**'
      - 'setup.py'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
      with:
        python-version: '3.12'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db

    - name: Login to GitHub Container Registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64 #,linux/arm/v7,linux/arm/v8
        tags: |
            ghcr.io/repository-service-tuf/repository-service-tuf-api:dev
        build-args: |
          RELEASE_VERSION=dev
