name: Build and Publish (dev) Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/publish_docker_dev.yml'
      - 'app.py'
      - 'entrypoint.sh'
      - 'Dockerfile'
      - 'requirements**'
      - 'repository_service_tuf_api/**'
      - 'setup.py'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: '3.10'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

    - name: Login to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
      with:
        context: .
        push: true
        tags: |
            ghcr.io/repository-service-tuf/repository-service-tuf-api:dev
        build-args: |
          RELEASE_VERSION=dev
