name: Publish Container Image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: "Image version"
        default: "dev"
        type: string
        required: False
  workflow_call:
    inputs:
      image_version:
        description: "Image version"
        default: "dev"
        type: string
        required: False

jobs:
  publish_container_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release tag
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0
        ref: ${{ inputs.image_version }}

    - name: Set default Python version
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
      with:
        python-version: '3.12'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64 #,linux/arm/v7,linux/arm/v8
        tags: |
            ghcr.io/repository-service-tuf/repository-service-tuf-api:${{ inputs.image_version }}
        build-args: |
          RELEASE_VERSION=${{ inputs.image_version }}
