name: Test Docker Image build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: '3.12'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

    - name: Build and push
      uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc
      with:
        context: .
        push: false
        platforms: linux/amd64,linux/arm64 #,linux/arm/v7,linux/arm/v8
        tags: |
            ghcr.io/repository-service-tuf/repository-service-tuf-api:test
        build-args: |
          RELEASE_VERSION=test
